services:
  - type: web
    name: parques-server
    runtime: python
    buildCommand: python -m pip install -e .
    startCommand: python -m server
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"

  - type: static
    name: parques-client
    buildCommand: cd client && npm ci && npm run build
    staticPublishPath: client/dist/spa
    envVars:
      - key: VITE_WS_URL
        value: wss://sd-parques.onrender.com
