services:
  - type: web
    name: parques-server
    runtime: python
    buildCommand: python -m pip install -e .
    startCommand: python -m server
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: DATABASE_URL
        value: postgresql://sd_parques_db_user:25f9QZW4Vhyi1KGbD2Lhbgm8zp0zgOv1@dpg-d8eivvf40ujc73dl4110-a.ohio-postgres.render.com/sd_parques_db

  - type: static
    name: parques-client
    buildCommand: cd client && npm ci && npm run build
    staticPublishPath: client/dist/spa
    envVars:
      - key: VITE_WS_URL
        value: wss://sd-parques.onrender.com
